### ISSUE TITLE
canot packaging .snap from electron

### ISSUE THREAD

**Issue by bobwatcherx** [canonical/snapcraft.io#4181]
I got an error when building electron js to snap, I followed the electron js documentation.  everything is normal but when building to snap .  that's not working. This is my error when using the snapcraft command in the terminal

electron docs : https://www.electronjs.org/docs/latest/tutorial/snapcraft

**my snap/snapcraft.yaml file :**
```
name: electron-packager-hello-world
version: '0.1'
summary: Hello World Electron app
description: |
  Simple Hello World Electron app as an example
base: core18
confinement: strict
grade: stable

apps:
  electron-packager-hello-world:
    command: electron-quick-start/electron-quick-start --no-sandbox
    extensions: [gnome-3-34]
    plugs:
    - browser-support
    - network
    - network-bind
    environment:
      # Correct the TMPDIR path for Chromium Framework/Electron to ensure
      # libappindicator has readable resources.
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  electron-quick-start:
    plugin: nil
    source: https://github.com/electron/electron-quick-start.git
    override-build: |
        npm install electron electron-packager
        npx electron-packager . --overwrite --platform=linux --output=release-build --prune=true
        cp -rv ./electron-quick-start-linux-* $SNAPCRAFT_PART_INSTALL/electron-quick-start
    build-snaps:
    - node/14/stable
    build-packages:
    - unzip
    stage-packages:
    - libnss3
    - libnspr4

```

command in terminal :
```
root@minto-Lenovo-V145-14AST:/home/minto/belajar/electronPro/electron1# snapcraft
Running with 'sudo' may cause permission errors and is discouraged. Use 'sudo' when cleaning.
Launching a VM.
Skipping pull electron-quick-start (already ran)
Skipping pull gnome-3-34-extension (already ran)
Skipping build electron-quick-start (already ran)
Skipping build gnome-3-34-extension (already ran)
Skipping stage electron-quick-start (already ran)
Skipping stage gnome-3-34-extension (already ran)
Skipping prime electron-quick-start (already ran)
Skipping prime gnome-3-34-extension (already ran)
The requested action has already been taken. Consider
specifying parts, or clean the steps you want to run again.
Snapping |                                                                                                     
Failed to create snap, snap command failed:
stdout:

stderr:
2022/12/16 10:31:37.502320 container.go:177: in snap "electron-packager-hello-world": "electron-quick-start" should be world-readable and executable, and isn't: drwx------
error: cannot pack "/root/prime": snap is unusable due to bad permissions
```
