### ISSUE TITLE
site warnings on core24

### ISSUE THREAD

**Issue by yvs2014** [canonical/snapcraft.io#4805]
the following snapcraft.yaml snippet for core24
```
base: core24
...
platforms:
  amd64:
  arm64:
  armhf:
```
triggers next message on snapcraft.io site at build stage:
`We have detected that your snap base is core20 or newer. This is not compatible with the i386 architecture, therefore that architecture will no longer be built.`

Not sure what's the warning origin is: some lint or site itself

p.s. snap building goes as usual
